### ISSUE TITLE
modularity versus automaton

### ISSUE THREAD

**Issue by bneron** [containers-ftw/SCI-F#6]
If I follow the SCI-F recommendations each steps of my pipeline is expose as an app.
Each step appear clearly, and the mechanism is relatively straight forward to transform my shell script 
(something very similar than the carrierseq example) in singularity sci-f.
But I loose the automatic chaining of the steps. 
Is there a way to execute the whole pipeline in one step?.
from the general %runscript or by adding %app workflow 
which could execute automatically each app ?

**Comment by vsoch** [comment]
this sounds more like an issue for a workflow manager, but I think there are a few ways to go about it if you want your app to (internally) call all steps in sequence. The typical / expected use case is that "some other third party" workflow manager executes the commands, externally, or even a basic bash script:

```
singularity run --app step1 container.simg
singularity run --app step2 container.simg
```
And you could simply write this into a `%help` section for the user, OR what I would try, if you want the chaining to happen when you run, it's a bit of a trick, but it basically calls run internally in context of each app:

```
%apprun

# Run step 1
export SINGULARITY_APPNAME=step1
/bin/bash /.singularity.d/actions/run

# Run step 3
export SINGULARITY_APPNAME=step2
/bin/bash /.singularity.d/actions/run
```
I'm actually curious to see how that would go! What it basically does it run the container in context of the app, meaning the right runscript and environment. What we would want to check is if we need to do any tweaking of the environment in the case that variables from step1 are still set for step2.

I really like the idea of a workflow - do you want to test the above, and if it seems reasonable, we could discuss what this `%app workflow` would look like?

**Comment by vsoch** [comment]
After you test, let's make an issue on the singularity board --> as that's where it will be implemented. https://www.github.com/singularityware/singularity 

I really like this idea! There are many workflow managers, but none of them live *inside* the image.

**Comment by bneron** [comment]
Thank's vanessa, it work perfectly. 
below my runscript which chain the different apps

```
%runscript
    workflow=( 'init' 'mapping' 'sam2bam' 'coverage' )

    for step in "${workflow[@]}"
    do
        echo "##################################"
        echo "  Entering in step: ${step}"
        echo "##################################"
        export SINGULARITY_APPNAME=${step}
        /bin/bash /.singularity.d/actions/run
    done
```

**Comment by vsoch** [comment]
oh this is super cool! And it would be useful for many users. Do you want to contribute the snippet as a markdown file to containers-ftw.github.io/apps ? I can help if needed.

**Comment by bneron** [comment]
Of course, what I need to do?

**Comment by vsoch** [comment]
Just wrote you up some instructions!

https://github.com/containers-ftw/apps#contribute-an-app

Let me know if I need to clarify anything, or if you have questions.

**Comment by bneron** [comment]
I try to write the snippet as markdown
```yaml
---
title:  "workflow-internal-serial"
date:   2017-11-08 00:00:00
author: Bertrand Neron
image: app/robots/robot95.png
tags: 
- scif
- singularity
- workflow
- pipeline
- bash
---
...
```
but when I run the test `python -m unittest -vv  tests.test_recipes`
I get an error
```
workflow/workflow-internal-serial:
image is not an allowed field.
```

**Comment by vsoch** [comment]
Ah I need to update the template! Looks like the final set is:

 -  title
 -  date
 - author
 - tags

sorry about that!

**Comment by vsoch** [comment]
Thanks again for this! :)
